### ISSUE TITLE
I Guess There is some Modification Required ( In C++ / C  Syntax Highlighting ) According to me 

### ISSUE THREAD

**Issue by Harshal0506** [ShrutiSolani/SyntaxHighlighter#1]
Its treating < and > in code as normal html tags 
![image](https://user-images.githubusercontent.com/66555099/122637928-d8160080-d10e-11eb-8c67-14b63cba48c3.png)

Because of which there is some issue in highlighting part 
I guess the steps u did for HTML language can be applied to c/ c++ too and it will resolve it 

![image](https://user-images.githubusercontent.com/66555099/122637901-b7e64180-d10e-11eb-97ab-3b219ffa559e.png)

Kindly Look into it

Thankyou 😃
It is a great project @ShrutiSolani

**Comment by ShrutiSolani** [comment]
Thanks for pointing it out. Actually, I am still working on it and haven't tested for C/C++ yet. Will keep in mind this issue. Again, Thanks 👍🏻
